# Numpy Tutorial

## Introduction

### What is Numpy?

Numpy is a multi-dimensional array library

### Why is Numpy fast?

1. It uses fixed types.    
2. Faster to read less bytes of memory.
3. No typechecking when iterating through objects.

For example: 

5 ---computer sees binary--> binary(00000101) ---NumPy---> Int32(00000000 00000000 00000000 00000101)/ Int8(a byte)(00000101)         

5 ---computer sees binary--> binary(00000101) ---Lists---> List uses a built in int type for integers, each of which uses 8 bytes, which consists of four things. (Suze, Reference Count, Object Type, Object Value)

4. NumPy utilizes contiguous memory.

### Applications of NumPy?

1. Mathematics (Matlab Replacement)
2. Plotting (Matplotlib)
3. Backend(Pandas, Connect 4, Digital Photography)
4. Machine Learning

## Load in Numpy (pip install numpy)

In [3]:
import numpy as np

### The Basics

In [12]:
a = np.array([1, 2, 3], dtype = 'int16')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimensions
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [18]:
# Get Type
a.dtype #data type

dtype('int16')

In [17]:
b.dtype

dtype('float64')

In [15]:
# Get size
a.itemsize #size of each item in the matrix, a int16 contains 2 bytes

2

In [16]:
b.itemsize

8

In [22]:
# Get total size 
a.size * a.itemsize #(3 * 2)
a.nbytes #the same thing

6

### Accessing/Changing specific elements, rows, columns, etc

In [23]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a.shape #It is a 2*7 matrix

(2, 7)

In [25]:
# Get a specific element [r, c]
a[1, 5]

13

In [26]:
a[1, -2]

13

In [27]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a spefic column 
a[:, 2]

array([ 3, 10])

In [32]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [33]:
a[1,5] = 20000
print(a)

[[    1     2     3     4     5     6     7]
 [    8     9    10    11    12 20000    14]]


In [34]:
a[:, 2] = [-3, -10]
print(a)

[[    1     2    -3     4     5     6     7]
 [    8     9   -10    11    12 20000    14]]


3D example

In [42]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [43]:
b.shape

(3, 2, 2)

In [44]:
# Get a specific element (work outside in)
b[2, 1, 0]

11

In [45]:
b[0, 0, :]

array([1, 2])

In [46]:
b[:, 1, :]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [47]:
b[:, :, 1]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [48]:
# Replace 
b[:, 1, :] = [[ 300,  400], [ 700,  800], [1100, 1200]]
print(b)

[[[   1    2]
  [ 300  400]]

 [[   5    6]
  [ 700  800]]

 [[   9   10]
  [1100 1200]]]


### Initializing Different Types of Arrays

In [49]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [57]:
# All 1s
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [60]:
# Any other number
np.full((2, 2), 99) 

array([[99, 99],
       [99, 99]])

In [62]:
# Any other number(full like)
np.full_like(a, 6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

In [64]:
# Random decimal numbers
np.random.rand(4, 2, 3)

array([[[0.79417124, 0.33025992, 0.93842748],
        [0.64795055, 0.46103578, 0.33094496]],

       [[0.76485217, 0.20614697, 0.50342105],
        [0.5403973 , 0.29702898, 0.43926608]],

       [[0.7685788 , 0.78404089, 0.94210021],
        [0.77791858, 0.24681444, 0.94646393]],

       [[0.75569705, 0.17197367, 0.61229265],
        [0.12243666, 0.48264864, 0.56939254]]])

In [65]:
np.random.random_sample(a.shape)

array([[0.27406005, 0.39229957, 0.1657325 , 0.01626294, 0.45820167,
        0.87402799, 0.14660483],
       [0.03231473, 0.18791118, 0.73435053, 0.79502467, 0.56050657,
        0.52063485, 0.02974537]])

In [72]:
# Random Integer values
np.random.randint(4, 8, size = (3, 3))

array([[4, 5, 4],
       [6, 7, 5],
       [5, 6, 6]])

In [74]:
# Identity Matrix
np.identity(5, dtype = 'int16')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [78]:
# Repeat an array
arr1 = np.array([1,2,3])
r1 = np.repeat(arr1, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [81]:
arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2, 3, axis = 0)
print(r2)
r3 = np.repeat(arr2, 5, axis = 1)
print(r3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]]


In [88]:
# Solving a problem 
matrix = np.ones((5, 5), dtype = 'int16')
matrix[1:4, 1:4] = np.zeros((3, 3), dtype = 'int16')
matrix[2, 2] = 9

In [90]:
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when copying arrays!!!

In [98]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [99]:
c = np.copy(a) #deep copy
b = a #aliasing

In [100]:
b

array([1, 2, 3])

In [101]:
b[2] = 90000

In [102]:
a

array([    1,     2, 90000])

In [103]:
c

array([1, 2, 3])

### Mathematics

In [104]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [105]:
a+2

array([3, 4, 5, 6])

In [106]:
a-2

array([-1,  0,  1,  2])

In [107]:
a*2

array([2, 4, 6, 8])

In [108]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [109]:
b = np.array([1, 0, 1, 0])

In [110]:
a + b

array([2, 2, 4, 4])

In [111]:
a ** 2

array([ 1,  4,  9, 16])

In [112]:
# Take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [113]:
a = np.ones((2, 3))
print(a)
b = np.full((3, 2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [115]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [116]:
np.matmul(b, a)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [117]:
c = np.identity(3)

In [118]:
# Find the determinant
np.linalg.det(c)

1.0

### Statistics

In [137]:
stats = np.array([[2, 50, 1],[6,11,8]])
stats

array([[ 2, 50,  1],
       [ 6, 11,  8]])

In [138]:
np.min(stats, axis = 1)

array([1, 6])

In [139]:
np.max(stats)

50

In [140]:
np.max(stats, axis = 0)

array([ 6, 50,  8])

In [141]:
np.sum(stats)

78

### Reorganizing Arrays

In [144]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
before.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [145]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [146]:
after = before.reshape((4, 2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [148]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [150]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [152]:
# Horizontal stacking cevtors
h1 = np.ones((2, 2))
h2 = np.zeros((2, 6))

np.hstack([h1, h2])

array([[1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0.]])

### Miscellaneous

#### Load data from file

In [158]:
filedata = np.genfromtxt('data.txt', delimiter=',')

In [162]:
filedata = filedata.astype('int32')

In [163]:
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Advanced Indexing

##### Boolean Masking and Advanced Indexing

In [164]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [165]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [170]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [180]:
np.all((filedata > 50) & (filedata < 100), axis = 1)

array([False, False, False])

In [166]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [168]:
a[a%2 != 0]

array([1, 3, 5, 7, 9])

In [181]:
# Challenge Problem

In [183]:
matrix = np.genfromtxt('data1.txt', delimiter = ',')

In [184]:
matrix = matrix.astype('int32')

In [185]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int32)

In [186]:
matrix[2:4, 0:2]

array([[11, 12],
       [16, 17]], dtype=int32)

In [190]:
matrix[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20], dtype=int32)

In [191]:
matrix[:, 3:][[0,4,5]]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int32)

In [194]:
matrix[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]], dtype=int32)

# YouTube Video Link: https://www.youtube.com/watch?v=QUT1VHiLmmI&ab_channel=freeCodeCamp.org